### ISSUE TITLE
pp 8 definition of inflection point

### ISSUE THREAD

**Issue by cbyeung** [mykelk/algforopt-reader-errata#1]
The third paragraph on page 8 reads "Figure 1.6 also has an inflection point where the *derivative is zero*," but the last sentence of the same paragraph contradicts this. Perhaps what was meant was that the *second* derivative is zero.

**Comment by mykelk** [comment]
The first sentence is correct, but I think the last sentence might be confusing. The last sentence is referring to the f' (not f) in the previous sentence, but the wording should probably be changed to make this more clear. Thoughts @tawheeler ?

**Comment by tawheeler** [comment]
That is right - I will put in a fix. Thanks!

**Comment by tawheeler** [comment]
@cbyeung if you would like to provide your name, I can put it in the acknowledgements.

**Comment by cbyeung** [comment]
My name is Brandon Yeung, but there is really no need to acknowledge me (unless you feel it is important to do so). I am just a student trying to learn, so thank you both for clarifying.
