### ISSUE TITLE
`eye` in (pseudo)code

### ISSUE THREAD

**Issue by tomerarnon** [mykelk/algforopt-reader-errata#2]
`eye` was discontinued in julia 1.0+ in favor of `I`. I think overall the book is going for 1.0+ style code.
 A quick search finds `eye` in the following algorithms:

- 6.3
- 6.4
- 8.9
- 9.13
- 11.5

**Comment by mykelk** [comment]
I think you might be looking at a course reader from last year. The final printed book has it updated to `I`.
